openapi: 3.0.0
info:
  contact:
    email: mohit3.sharma@lntinfotech.com
  description: This is a simple API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Simple API
  version: 1.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/mohit3.sharma/SimpleAPI/1.0.0
tags:
- description: Operations available to regular developers
  name: developers
paths:
  /health:
    get:
      description: method gives health status of app
      operationId: healthChecking
      parameters:
      - description: param with App name
        explode: true
        in: query
        name: appName
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: App up or down status
        "400":
          description: bad input parameter
      summary: health check API
      tags:
      - developers
      x-accepts: application/json
      x-tags:
      - tag: developers
components:
  schemas: {}
